### PR TITLE
Fix static initialization

### LINKED ISSUE #799: static logger initialization and subsequent static initializations using logging.get is undefined behavior
We initialize `villas::logging` as a static member in `log.cpp`. At the same time several other objects are created as static objects. Some of them (e.g., `MemoryManager`, `DirectedGraph`, `HostRamAllocator`) use the static object to create their own logging instances, i.e., `villas::logging.get()`.
The initialization order of these objects is undefined and thus what we are doing is undefined behavior.
If I activate link time optimization (`-lto`) I get segmentation faults because the initialization order is different.

I would suggest to move the initialization of these objects to an explicit initialization function, where we can make the initialization order explicit and call this function for example from a library constructor or via a single static initialization.

I only researched this briefly so I may have misunderstood some of this.

### PR DESCRIPTION
**Pull request by n-eiling**
fixes #799 

I replaced the static constructor call of `villas::logging` and `HostRamAllocator::allocator` to a function that does lazy initialization (i.e., on the first call).
This avoid the undefined behavior mentioned in the issue and even avoid an explicit initialization order.
The implementation leak heap memory that will be implicitly cleaned up when the application finished. While currently not a problem, the destructors of Log and HostRamAllocator should not assume the existence of other static objects, because the deinitialization order is still undefined.

I implemented the C++ Foundaitions recommendation for this issue (see https://isocpp.org/wiki/faq/ctors#static-init-order)

This PR allows using link time optimization (`-lto` gcc flag) with VILLASnode.

### CODE REVIEW

File: common/include/villas/memory.hpp [hunk 1]
```diff
@@ -249,10 +249,12 @@ class HostRam {
     allocateBlock(size_t size);
   };
 
-  static HostRamAllocator &getAllocator() { return allocator; }
-
-private:
-  static HostRamAllocator allocator;
+  static HostRamAllocator &getAllocator() {
```
Comment (stv0g) [inline common/include/villas/memory.hpp:252]: Could we use the same approach for the logging class as well?

E.g. have a static function, with a static private/projected member as singleton?

```cpp
Log::getLogger("some_name")
```

is nicer than:

```cpp
logging().get("some_name")
```

I also prefer to have an harmonized way to create those singletons.

**Review by stv0g — CHANGES_REQUESTED** [review]
I only have a small request :)

But thanks a lot for the effort and debugging the issue :)

File: common/include/villas/memory.hpp (hunk 1 above)
Comment (n-eiling) [reply common/include/villas/memory.hpp:252]: ok. I wanted to be minimally invasive, but this sounds sensible.

**Comment by n-eiling** [comment]
I updated the PR. Was this what you thought of?

**Comment by stv0g** [comment]
Yes great :)

Just wondering did you want to keep the inconsistency intentionally?

`HostRamAllocator::getAllocator` vs `Log::get()`

I would opt for one of the following:

- `HostRamAllocator::get()` & `Log::get()`
- `HostRamAllocator::getAllocator()` & `Log::getLogger()`

**Comment by n-eiling** [comment]
Hmm difficult ... The choice is
`HostRam::HostRamAllocator::getInstance()`
or
`HostRam::HostRamAllocator::get()`
or
`HostRam::getAllocator()`

I think I still prefer the last one.
For Log there is now
`Log::getInstance()` to get what was originally `villas::logger`, and `Log::get()` for what was originally `villas::logger.get()`. This avoids one function call compared to `Log::getInstance().get()`, which should be slightly better for performance.

**Review by windrad6 — APPROVED** [review]

**Comment by stv0g** [comment]
> I think I still prefer the last one.

Okay, then lets go also with `Log::getLogger()`. Especially if there is also `Log::getInstance()`. Because otherwise, I would ask myself: what do we `get()` here?

**Comment by n-eiling** [comment]
Was this ok now, or do you want me to change anything?

**Comment by n-eiling** [comment]
@stv0g

**Review by stv0g — APPROVED** [review]
